"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.12.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(3zvwmq322-ptb(tzf$hd=w#0x=exhm3+1wvb!dzb(c5z7=il='

# SECURITY WARNING: don't run with debug turned on in production!
# Use environment variable `DJANGO_DEBUG` to control debug mode. Defaults to True for development.
DEBUG = os.environ.get('DJANGO_DEBUG', os.environ.get('DEBUG', 'True')).lower() in ('1', 'true', 'yes')

# Configure allowed hosts via environment variable `ALLOWED_HOSTS`, comma-separated. Defaults to empty list.
ALLOWED_HOSTS = [h for h in os.environ.get('ALLOWED_HOSTS', '').split(',') if h]


LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'core.tracing': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'drf_spectacular',
    'core',
    'corsheaders',
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'URL_FORMAT_OVERRIDE': '_format',
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'Fe y Alegria API',
    'DESCRIPTION': 'Documentacion OpenAPI del backend de Fe y Alegria',
    'VERSION': '1.0.0',
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'core.middleware.TimezoneMiddleware',
    'core.middleware.LogMiddleware',
    'core.middleware.ErrorMiddleware',
    'core.middleware.AuthMiddleware',
]

# CORS configuration: in production set CORS_ALLOW_ALL_ORIGINS=false and provide CORS_ALLOWED_ORIGINS
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'True').lower() in ('1', 'true', 'yes')
CORS_ALLOWED_ORIGINS = [o for o in os.environ.get('CORS_ALLOWED_ORIGINS', '').split(',') if o]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_HEADERS = [
    'accept',
    'authorization',
    'content-type',
    'x-requested-with',
    'x-timezone',
]
API_DOCS_PUBLIC = DEBUG or os.environ.get('API_DOCS_PUBLIC', '').lower() == 'true'
AUTH_TOKEN_MAX_AGE = int(os.environ.get('AUTH_TOKEN_MAX_AGE', 60 * 60 * 24))
AUTH_TOKEN_SALT = os.environ.get('AUTH_TOKEN_SALT', 'ue.panama.auth')

# ── Correo saliente (SMTP) ───────────────────────────────────────────────────
# Para Gmail usa una "contrasena de aplicacion" en EMAIL_HOST_PASSWORD.
EMAIL_BACKEND = os.environ.get('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', 587))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True').lower() in ('1', 'true', 'yes')
EMAIL_USE_SSL = os.environ.get('EMAIL_USE_SSL', 'False').lower() in ('1', 'true', 'yes')
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', 20))
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL') or EMAIL_HOST_USER or 'no-reply@localhost'
EMAIL_SUBJECT_PREFIX = os.environ.get('EMAIL_SUBJECT_PREFIX', '[U.E. Fe y Alegria] ')

# ─ Autenticacion en dos pasos (2FA / OTP) ───────────────────────────────────
OTP_ISSUER = os.environ.get('OTP_ISSUER', 'U.E. Fe y Alegria')
OTP_TTL_MINUTOS = int(os.environ.get('OTP_TTL_MINUTOS', 10))
OTP_LOGIN_TTL_MINUTOS = int(os.environ.get('OTP_LOGIN_TTL_MINUTOS', 5))
OTP_MAX_INTENTOS = int(os.environ.get('OTP_MAX_INTENTOS', 5))
OTP_CODIGO_DIGITOS = int(os.environ.get('OTP_CODIGO_DIGITOS', 6))
OTP_2FA_POR_DEFECTO = os.environ.get('OTP_2FA_POR_DEFECTO', 'True').lower() in ('1', 'true', 'yes')
OTP_TOTP_INTERVALO = int(os.environ.get('OTP_TOTP_INTERVALO', 30))
OTP_TOTP_VENTANA = int(os.environ.get('OTP_TOTP_VENTANA', 1))
OTP_PENDING_TOKEN_MAX_AGE = int(os.environ.get('OTP_PENDING_TOKEN_MAX_AGE', 60 * 10))
AUTH_TEMP_PASSWORD_MAX_AGE = int(os.environ.get('AUTH_TEMP_PASSWORD_MAX_AGE', 60 * 60 * 24 * 3))
FRONTEND_BASE_URL = os.environ.get('FRONTEND_BASE_URL', 'http://localhost:3000')

# Auth cookie settings
AUTH_COOKIE_NAME = os.environ.get('AUTH_COOKIE_NAME', 'auth_token')
AUTH_COOKIE_SECURE = not DEBUG  # True in production with HTTPS
AUTH_COOKIE_HTTPONLY = True
AUTH_COOKIE_SAMESITE = 'Lax'
ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.environ.get('DB_NAME'),
        'USER': os.environ.get('DB_USER'),
        'PASSWORD': os.environ.get('DB_PASSWORD'),
        'HOST': os.environ.get('DB_HOST'),
        'PORT': os.environ.get('DB_PORT'),
        'CONN_MAX_AGE': 300,
        'OPTIONS': {
            'connect_timeout': 180,
            'keepalives': 1,
            'keepalives_idle': 30,
            'keepalives_interval': 10,
            'keepalives_count': 5,
        },
    }
}
# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'America/La_Paz'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
