[pytest]
DJANGO_SETTINGS_MODULE = config.test_settings
python_files = test_*.py
python_classes = Test*
python_functions = test_*
addopts = 
    --verbose
    --strict-markers
    --tb=short
    --timeout=15
    --timeout-method=thread
    --cov=core
    --cov-report=html
    --cov-report=term-missing
    --nomigrations

testpaths = core/tests core/test_global.py

markers =
    django_db: Marca tests que usan la BD de Django
    slow: Marca tests lentos
    integration: Tests de integraci├│n
    unit: Tests unitarios
