# Generated by Django 5.2.12 on 2026-05-28 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Areas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'areas',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'cursos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DimensionesEvaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True)),
                ('orden', models.IntegerField()),
            ],
            options={
                'db_table': 'dimensiones_evaluacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rude', models.TextField(unique=True)),
                ('ci', models.TextField(unique=True)),
                ('primer_apellido', models.TextField()),
                ('segundo_apellido', models.TextField(blank=True, null=True)),
                ('nombres', models.TextField()),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('genero', models.TextField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('Otro', 'Otro')], null=True)),
                ('pais_nacimiento', models.TextField(default='Bolivia')),
                ('tiene_discapacidad', models.BooleanField(default=False)),
                ('tipo_discapacidad', models.TextField(blank=True, null=True)),
                ('tiene_tea', models.BooleanField(default=False)),
                ('dificultad_aprendizaje', models.TextField(blank=True, null=True)),
                ('estado', models.TextField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('retirado', 'Retirado')], default='activo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'estudiantes',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Grados',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('numero', models.IntegerField()),
            ],
            options={
                'db_table': 'grados',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Niveles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'niveles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Paralelos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'paralelos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Periodos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('gestion', models.IntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('estado', models.TextField(choices=[('pendiente', 'Pendiente'), ('activo', 'Activo'), ('cerrado', 'Cerrado')], default='pendiente')),
                ('habilitado_en', models.DateTimeField(blank=True, null=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'periodos',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'roles',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Tutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ci', models.TextField(unique=True)),
                ('tipo_documento', models.TextField(default='CI')),
                ('primer_apellido', models.TextField()),
                ('segundo_apellido', models.TextField(blank=True, null=True)),
                ('nombres', models.TextField()),
                ('parentesco', models.TextField(blank=True, null=True)),
                ('celular', models.TextField(blank=True, null=True)),
                ('idioma_frecuente', models.TextField(blank=True, null=True)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'tutores',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='DocenteAsignacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areas')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cursos')),
            ],
            options={
                'db_table': 'docente_asignacion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_actividad', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dimensionesevaluacion')),
                ('docente_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docenteasignacion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodos')),
            ],
            options={
                'db_table': 'actividades',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='cursos',
            name='grado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.grados'),
        ),
        migrations.CreateModel(
            name='Horarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(1, 'Lunes'), (2, 'Martes'), (3, 'Miércoles'), (4, 'Jueves'), (5, 'Viernes')])),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('aula', models.TextField(blank=True, null=True)),
                ('docente_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docenteasignacion')),
            ],
            options={
                'db_table': 'horarios',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='grados',
            name='nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.niveles'),
        ),
        migrations.AddField(
            model_name='cursos',
            name='paralelo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.paralelos'),
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('activo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.roles')),
            ],
            options={
                'db_table': 'usuarios',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='periodos',
            name='cerrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_cerrados', to='core.usuarios'),
        ),
        migrations.AddField(
            model_name='periodos',
            name='habilitado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_habilitados', to='core.usuarios'),
        ),
        migrations.CreateModel(
            name='Licencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('requiere_respaldo', models.BooleanField(default=False)),
                ('respaldo_presentado', models.BooleanField(default=False)),
                ('estado', models.TextField(choices=[('pendiente', 'Pendiente'), ('aprobada', 'Aprobada'), ('rechazada', 'Rechazada')], default='pendiente')),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
                ('tutor_solicitante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.tutores')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_aprobadas', to='core.usuarios')),
                ('regente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='licencias_regentadas', to='core.usuarios')),
            ],
            options={
                'db_table': 'licencias',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='docenteasignacion',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios'),
        ),
        migrations.CreateModel(
            name='ActividadNotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
                ('modificado_en', models.DateTimeField(auto_now=True)),
                ('actividad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.actividades')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
            ],
            options={
                'db_table': 'actividad_notas',
                'managed': True,
                'unique_together': {('actividad', 'estudiante')},
            },
        ),
        migrations.CreateModel(
            name='Inscripciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gestion', models.IntegerField()),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.TextField(choices=[('activo', 'Activo'), ('retirado', 'Retirado'), ('transferido', 'Transferido')], default='activo')),
                ('curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cursos')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
            ],
            options={
                'db_table': 'inscripciones',
                'managed': True,
                'unique_together': {('estudiante', 'gestion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='grados',
            unique_together={('nivel', 'numero')},
        ),
        migrations.AlterUniqueTogether(
            name='cursos',
            unique_together={('grado', 'paralelo')},
        ),
        migrations.CreateModel(
            name='NotaObservaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicador', models.TextField(blank=True, choices=[('PA', 'PA'), ('SA', 'SA'), ('A', 'A'), ('EA', 'EA')], null=True)),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('docente_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docenteasignacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodos')),
            ],
            options={
                'db_table': 'nota_observaciones',
                'managed': True,
                'unique_together': {('estudiante', 'docente_asignacion', 'periodo')},
            },
        ),
        migrations.CreateModel(
            name='DimensionConfigPeriodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntaje_maximo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dimension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.dimensionesevaluacion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodos')),
            ],
            options={
                'db_table': 'dimension_config_periodo',
                'managed': True,
                'unique_together': {('periodo', 'dimension')},
            },
        ),
        migrations.CreateModel(
            name='EstudianteTutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_principal', models.BooleanField(default=False)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tutores')),
            ],
            options={
                'db_table': 'estudiante_tutor',
                'managed': True,
                'unique_together': {('estudiante', 'tutor')},
            },
        ),
        migrations.CreateModel(
            name='PeriodoCierreDocente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cerrado_en', models.DateTimeField(auto_now_add=True)),
                ('reabierto_en', models.DateTimeField(blank=True, null=True)),
                ('docente_asignacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.docenteasignacion')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.periodos')),
                ('cerrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cierres_realizados', to='core.usuarios')),
                ('reabierto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cierres_reabiertos', to='core.usuarios')),
            ],
            options={
                'db_table': 'periodo_cierre_docente',
                'managed': True,
                'unique_together': {('periodo', 'docente_asignacion')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='docenteasignacion',
            unique_together={('usuario', 'curso', 'area', 'gestion')},
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tabla', models.TextField()),
                ('registro_id', models.IntegerField()),
                ('accion', models.TextField()),
                ('datos_anterior', models.JSONField(blank=True, null=True)),
                ('datos_nuevo', models.JSONField(blank=True, null=True)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuarios')),
            ],
            options={
                'db_table': 'audit_log',
                'managed': True,
                'indexes': [models.Index(fields=['tabla', 'registro_id'], name='audit_log_tabla_652106_idx'), models.Index(fields=['usuario'], name='audit_log_usuario_5aa78d_idx'), models.Index(fields=['fecha_cambio'], name='audit_log_fecha_c_d0ad7b_idx')],
            },
        ),
        migrations.CreateModel(
            name='Asistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.TextField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('con_licencia', 'Con Licencia')], default='presente')),
                ('tipo', models.TextField(choices=[('administrativa', 'Administrativa'), ('por_asignacion', 'Por Asignación')], default='administrativa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('docente_asignacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.docenteasignacion')),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.estudiantes')),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'asistencias',
                'managed': True,
                'unique_together': {('estudiante', 'docente_asignacion', 'fecha', 'tipo')},
            },
        ),
    ]
