# Generated by Django 5.2.12 on 2026-05-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_constraints_and_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividades',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='asistencias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tutores',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
