# Generated by Django 5.2.12 on 2026-05-29 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_soft_delete_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodos',
            name='enviado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='periodos',
            name='enviado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='periodos_enviados', to='core.usuarios'),
        ),
        migrations.AddField(
            model_name='periodos',
            name='marcado_como_enviado',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExportEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docente_asignacion_id', models.IntegerField(blank=True, null=True)),
                ('formato', models.TextField()),
                ('filtros', models.JSONField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('periodo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.periodos')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuarios')),
            ],
            options={
                'db_table': 'export_event',
                'managed': True,
            },
        ),
    ]
