# Generated by Django 5.2.12 on 2026-05-29 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_periodos_enviado_en_periodos_enviado_por_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionEscuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(default='Unidad Educativa')),
                ('direccion', models.TextField(blank=True, default='')),
                ('telefono', models.TextField(blank=True, default='')),
                ('email', models.TextField(blank=True, default='')),
                ('ciudad', models.TextField(blank=True, default='')),
                ('gestion_actual', models.IntegerField(blank=True, null=True)),
                ('escala_aprobacion', models.DecimalField(decimal_places=2, default=51.0, max_digits=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'configuracion_escuela',
                'managed': True,
            },
        ),
    ]
