# Generated by Django 5.2.12 on 2026-05-29 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_configuracion_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuarios',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
