# Generated by Django 5.2.12 on 2026-05-29 19:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_catalog_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividadnotas',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='estudiantetutor',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='horarios',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='inscripciones',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='licencias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='periodos',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='roles',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.CreateModel(
            name='DocenteAsistencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.TextField(choices=[('presente', 'Presente'), ('ausente', 'Ausente'), ('con_licencia', 'Con Licencia')], default='presente')),
                ('observacion', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_attendances_registered', to='core.usuarios')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'docente_asistencias',
                'managed': True,
                'unique_together': {('usuario', 'fecha')},
            },
        ),
        migrations.CreateModel(
            name='TokenBlacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(unique=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('expira_en', models.DateTimeField()),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'token_blacklist',
                'managed': True,
                'indexes': [models.Index(fields=['token'], name='token_black_token_6a50c6_idx'), models.Index(fields=['expira_en'], name='token_black_expira__8662ae_idx')],
            },
        ),
    ]
