# Generated by Django 5.2.12 on 2026-05-30 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_observaciones_estudiantes'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.TextField()),
                ('method', models.TextField()),
                ('ip_address', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.usuarios')),
            ],
            options={
                'db_table': 'access_log',
                'managed': True,
                'indexes': [models.Index(fields=['usuario'], name='access_log_usuario_8feef9_idx'), models.Index(fields=['path'], name='access_log_path_5673c9_idx'), models.Index(fields=['created_at'], name='access_log_created_830860_idx')],
            },
        ),
    ]
