# Generated by Django 5.2.12 on 2026-06-03 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_configuracion_escuela_fix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensaje', models.TextField()),
                ('tipo', models.TextField(choices=[('info', 'Informativo'), ('warning', 'Advertencia'), ('alert', 'Alerta')], default='info')),
                ('leida', models.BooleanField(default=False)),
                ('link', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to='core.usuarios')),
            ],
            options={
                'db_table': 'notificaciones',
                'ordering': ['-created_at'],
                'managed': True,
            },
        ),
    ]
