# Generated by Django 5.2.12 on 2026-06-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notificaciones'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DocenteAsistencias',
        ),
    ]
