# Generated by Django 5.2.12 on 2026-06-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_delete_docenteasistencias'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='apellido',
            new_name='primer_apellido',
        ),
        migrations.RemoveField(
            model_name='usuarios',
            name='nombre_completo',
        ),
        migrations.AddField(
            model_name='usuarios',
            name='segundo_apellido',
            field=models.TextField(blank=True, null=True),
        ),
    ]
