# Generated by Django 5.2.12 on 2026-06-09 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_delete_observacionesestudiantes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='registro_id',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='docenteasignacion',
            unique_together={('curso', 'area', 'gestion')},
        ),
    ]
