# Generated by Django 5.2.12 on 2026-06-18 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_inscripciones_estudiante_gestion_index'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='actividadnotas',
            index=models.Index(fields=['estudiante'], name='idx_notas_estudiante'),
        ),
    ]
